spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.240.210.206:3306/ssmhxy?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

server:
  port: 8080

logging:
  level:
    com:
      neusoft:
        newsroom: INFO
      mypackage:
        domain:
          persistence: DEBUG
    org:
      hibernate: ERROR
      springframework:
        security: INFO